name: 'Check Licenses'
description: 'Check used licences'
inputs:
  dependency-manager:
    description: 'Dependency manager used (npm, maven, gradle)'
    required: true
    default: 'maven'
  github-token:
    description: 'The github token to commit license cache'
    required: true
  working-directory:
    description: 'The directory to run the license checks in'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      if: inputs.dependency-manager == 'npm'
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
    - name: disable post and preinstall scripts
      shell: bash
      run: npm config set ignore-scripts true
      if: inputs.dependency-manager == 'npm'
    - name: npm install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
      if: inputs.dependency-manager == 'npm'

    - name: Check workspace .licensed.yml existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: ".licensed.yml"
    - name: Merge licensed.yml files
      if: steps.check_files.outputs.files_exists == 'true'
      shell: bash
      run: yq eval-all -i 'select(fileIndex == 0) *d select(fileIndex == 1)' ${{ github.action_path }}/.licensed.yml ${{ inputs.working-directory }}/.licensed.yml

    - name: copy .licensed.yml
      shell: bash
      run: cp ${{ github.action_path }}/.licensed.yml /tmp/.licensed.yml

    # setup ruby environment before running licensee/setup-licensed
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        working-directory: ${{ inputs.working-directory }}

    - uses: licensee/setup-licensed@v1.3.2
      with:
        version: 5.x
    - uses: github/licensed-ci@v1
      id: licensed
      with:
        github_token: ${{ inputs.github-token }}
        config_file: /tmp/.licensed.yml
