name: 'Check Licenses'
description: 'Check used licences'
inputs:
  dependency-manager:
    description: 'Dependency manager used (npm, maven, gradle)'
    required: true
    default: 'maven'
  github-token:
    description: 'The github token to commit license cache'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      if: inputs.dependency-manager == 'npm'
      with:
        node-version: '14'
        cache: 'npm'
    - name: disable post and preinstall scripts
      shell: bash
      run: npm config set ignore-scripts true
      if: inputs.dependency-manager == 'npm'
    - name: npm install
      shell: bash
      run: npm ci
      if: inputs.dependency-manager == 'npm'

    - name: Check workspace .licensed.yml existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: ".licensed.yml"
    - name: Merge licensed.yml files
      if: steps.check_files.outputs.files_exists == 'true'
      shell: bash
      run: yq eval-all -i 'select(fileIndex == 0) *d select(fileIndex == 1)' ${{ github.action_path }}/.licensed.yml .licensed.yml

    - name: copy .licensed.yml
      shell: bash
      run: cp ${{ github.action_path }}/.licensed.yml /tmp/.licensed.yml

    - uses: jonabc/setup-licensed@v1
      with:
        version: 3.x
    - uses: jonabc/licensed-ci@v1
      id: licensed
      with:
        github_token: ${{ inputs.github-token }}
        config_file: /tmp/.licensed.yml
